spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/CEFETPLAY
spring.datasource.username=root
spring.datasource.password=nenem_baielsaul
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#[SENHA_DO_BANCO]
#[NOME_DO_BANCO]




















#spring.datasource.url = jdbc : h2 : mem : testdb
#spring.datasource.driverClassName = org.h2.Driver
#spring.datasource.username = sa
#spring.datasource.password =
#spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled = true